# Generated by Django 4.0.1 on 2022-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otp_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_forgot',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
