# Generated by Django 4.0.2 on 2022-02-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_forgot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgot',
            old_name='email',
            new_name='email_forgot',
        ),
    ]
